SELECT 
    _FIVETRAN_ID,
    ITEM_NAME,
    REMOVE_FROM_CART_QUANTITY,
    ADD_TO_CART_QUANTITY,
    PRICE_PER_UNIT,
    SESSION_ID,
    ITEM_VIEW_AT AS ITEM_VIEW_AT_TS,
    _FIVETRAN_DELETED,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{source("snowflake_db", "ITEM_VIEWS")}}