SELECT
EMPLOYEE_ID AS EMPLOYEE_ID,
DATE(SUBSTRING(HIRE_DATE,5,11)) AS HIRE_DATE,
NAME AS NAME,
CITY AS CITY,
ADDRESS AS ADDRESS,
TITLE AS TITLE,
ANNUAL_SALARY AS ANNUAL_SALARY,
_FILE AS _FILE,
_Line AS _Line,
_MODIFIED AS _MODIFIED,
_FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
--FROM FIVETRAN_DATABASE.DRIVE_SCHEMA.HR_JOINS
FROM {{source('google_drive', 'HR_JOINS')}}