SELECT 
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
    RETURNED_AT as RETURNED_AT,
    ORDER_ID as ORDER_ID,
    IS_REFUNDED as IS_REFUNDED,
FROM {{source("google_drive", "RETURNS")}}

