SELECT
CLIENT_NAME,
ORDER_ID, 
ORDER_AT AS ORDER_AT_TS,
PAYMENT_METHOD, 
CAST( SUBSTRING(SHIPPING_COST, 5) AS REAL)  AS SHIPPING_COST_USD, 
TAX_RATE,
SESSION_ID, 
STATE, 
PAYMENT_INFO, 
SHIPPING_ADDRESS, 
PHONE, 
_FIVETRAN_DELETED, 
_FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
_FIVETRAN_ID
--FROM FIVETRAN_DATABASE.SNOWFLAKE_DB_WEB_SCHEMA.ORDERS
FROM {{source('snowflake_db', 'ORDERS')}}