version: 2

sources:
  - name: google_drive
    database: FIVETRAN_DATABASE
    schema: DRIVE_SCHEMA
    tables:
      - name: EXPENSES
      - name: RETURNS
      - name: HR_JOINS
      - name: HR_QUITS

  - name: snowflake_db
    database: FIVETRAN_DATABASE
    schema: SNOWFLAKE_DB_WEB_SCHEMA
    tables:
      - name: ITEM_VIEWS
      - name: SESSIONS
      - name: ORDERS
      - name: PAGE_VIEWS